---
- name: Configura o ambiente de desenvolvimento
  hosts: dev
  gather_facts: true

  pre_tasks:
    - name:  Dependencias de desenvolvimento
      become: true
      import_tasks: tasks/python_env.yml

  roles:
    - role: staticdev.pyenv
      pyenv_env: user
      pyenv_global:
        - 3.11.0
      pyenv_python_versions:
        - 3.11.0
  
  tasks:
    - name: Configurando o vim
      become: true
      import_tasks: tasks/vim_config.yml
