---
- name: Instalação do nginx
  hosts: arch
  become: yes

  tasks:

    - name: Instalaçao do nginx
      package:
        state: present
        name: nginx


    - name: Inicializaçao do nginx
      systemd:
        state: started
        name: nginx
